### ISSUE TITLE
Configure Error

### ISSUE THREAD

**Issue by renodesper** [jonhoo/wp2ghost#1]
I got this error when executing "npm install":

```
> node-expat@2.0.0 install /home/renodesper/wp2ghost-master/node_modules/xml-stream/node_modules/node-expat
> node-gyp rebuild

gyp: /home/renodesper/.node-gyp/0.10.26/common.gypi not found (cwd: /home/renodesper/wp2ghost-master/node_modules/xml-stream/node_modules/node-expat) while reading includes of binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:337:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Linux 3.13.6-1-ARCH
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/renodesper/wp2ghost-master/node_modules/xml-stream/node_modules/node-expat
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.12.2
gyp ERR! not ok 
npm ERR! Error: ENOENT, lstat '/home/renodesper/wp2ghost-master/node_modules/xml-stream/node_modules/iconv/deps/libiconv/libcharset/tools/glibc-2.2-XF86-3.3.6'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.13.6-1-ARCH
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/renodesper/wp2ghost-master
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! path /home/renodesper/wp2ghost-master/node_modules/xml-stream/node_modules/iconv/deps/libiconv/libcharset/tools/glibc-2.2-XF86-3.3.6
npm ERR! fstream_path /home/renodesper/wp2ghost-master/node_modules/xml-stream/node_modules/iconv/deps/libiconv/libcharset/tools/glibc-2.2-XF86-3.3.6
npm ERR! fstream_type File
npm ERR! fstream_class FileWriter
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! fstream_stack /usr/lib/node_modules/npm/node_modules/fstream/lib/writer.js:284:26
npm ERR! fstream_stack Object.oncomplete (fs.js:107:15)
npm ERR! node-expat@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the node-expat@2.0.0 install script.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.13.6-1-ARCH
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! cwd /home/renodesper/wp2ghost-master
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.3
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/renodesper/wp2ghost-master/npm-debug.log
npm ERR! not ok code 0
```

**Comment by codito** [comment]
I had to set the default python for node to python2 for `npm install` to work (on Arch x64 box).

`npm config set python /usr/bin/python2`
