### ISSUE TITLE
Will not install

### ISSUE THREAD

**Issue by rezn8d** [jonhoo/wp2ghost#5]
npm install failure... please update

**Comment by jonhoo** [comment]
`npm install` works fine here. What error are you seeing?

**Comment by shuron** [comment]
What i'm seeing:
```bash
b:\tmp\wp2ghost-master>npm install
npm WARN package.json wp2ghost@ No license field.
-
> node-expat@2.3.10 install b:\tmp\wp2ghost-master\node_modules\xml-stream\node_modules\node-expat
> node-gyp rebuild


b:\tmp\wp2ghost-master\node_modules\xml-stream\node_modules\node-expat>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd b:\tmp\wp2ghost-master\node_modules\xml-stream\node_modules\node-expat
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

> iconv@2.1.11 install b:\tmp\wp2ghost-master\node_modules\xml-stream\node_modules\iconv
> node-gyp rebuild


b:\tmp\wp2ghost-master\node_modules\xml-stream\node_modules\iconv>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild) 
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.3.9600
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd b:\tmp\wp2ghost-master\node_modules\xml-stream\node_modules\iconv
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! node-expat@2.3.10 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-expat@2.3.10 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the node-expat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-expat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     b:\tmp\wp2ghost-master\npm-debug.log
```

**Comment by jonhoo** [comment]
> Can't find Python executable "python"

You need to have python installed to build node-gyp, which is used by the XML library used by wp2ghost.

**Comment by shuron** [comment]
Ok, will try it on linux... with python.

**Comment by shuron** [comment]
Worked on ubuntu. thx
